extends Node

enum card_type {RED_POTION, GREEN_POTION, BLUE_POTION, DOOR_KEY}

enum audio_type {SWORD, BAT_DYING, BAT_ATTACKING, SPIDER_DYING, SPIDER_ATTACKING, COIN_COLLECTING, SHOP_KEEPER, NEXT_LEVEL, HEROE_DYING}
